### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by degaurab** [danhigham/concourse-vis#3]
**File**

 /Users/pivotal/.atom/packages/concourse-vis/node_modules/d3/d3.js:1427

**Stack Trace**

```
TypeError: Cannot read property '0' of null
    at translateTo (/Users/pivotal/.atom/packages/concourse-vis/node_modules/d3/d3.js:1427:18)
    at SVGSVGElement.mousewheeled (/Users/pivotal/.atom/packages/concourse-vis/node_modules/d3/d3.js:1564:7)
    at SVGSVGElement.__onwheel.zoom (/Users/pivotal/.atom/packages/concourse-vis/node_modules/d3/d3.js:1120:18)
```

**Comment by danhigham** [comment]
Hey Gaurab, I don't see any issues with zooming in and out. Can you provide me with a way to reproduce?

**Comment by danhigham** [comment]
Going to close this. Please re-open if you can find a way to reproduce the issue.
